### ISSUE TITLE
Random white flashes in between playlist items.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-image#102]
**How to recreate**
Assign multiple Image Widgets w/images to a placeholder in two presentations. (Test presentations [here](https://apps.risevision.com/editor/workspace/28e2500a-ed80-4ac7-8434-dd40131ff9f9/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55) and [here](https://apps.risevision.com/editor/workspace/f703276f-217b-404d-830d-f596767955c3/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55).)
Set the transition of those placeholders to "None".
Assign both presentations to a schedule.
Assign schedule to a display.

**What happens**
The presentation will play through the placeholder items, occasionally, the screen will flash white in between the placeholder items.

**What should happen**
1) The presentation should
 - Play image after image with no white flash

2) The schedule should
 - Play scheduled presentations no white flash

**Notes**
Video [here](http://www.screencast.com/t/NvlaMmBJ)
Schedule [here](https://apps.risevision.com/schedules/details/600c0db4-bfef-4ff7-847f-eaa2f6d74454?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55)
I have attempted to recreate with calendar/video/web page widget and I am not able to recreate. 

**Operating System:** 64-bit Microsoft Windows 10 Pro
**Player Version:** RisePlayerElectron 2016.10.13.00.42
**Viewer Version:** 2-00-201610041830
**Browser Version:** Chrome 52.0.2743.82

**Comment by donnapep** [comment]
@btfrise If there's a white flash _between_ plays of the Image Widget, then to me that sounds like more of a Viewer issue? Widget can't really control what happens during the transitioning.

**Comment by donnapep** [comment]
@ezequielc What do you think about this issue? It sounds like it has more to do with Viewer than with the Image Widget.

**Comment by ezequielc** [comment]
@donnapep I am not sure. The issue was initially opened in Viewer (https://github.com/Rise-Vision/viewer/issues/141) but it seems that it only happens with Image Widget. Could it be something during the widget initialization? Thanks

**Comment by donnapep** [comment]
@ezequielc OK, if you guys have already looked into it, I'll take a shot on the Widget side. Thx.

**Comment by alanclayton** [comment]
Fix released.
