### ISSUE TITLE
SVG's are not showing up reliably in a Presentation on a Display

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-image#110]
<b>How it works now:</b>
1. Put <a href="https://apps.risevision.com/editor/workspace/bfd86f2c-1430-49b5-875c-6c541a7e7eb1/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a> into a Schedule, and play it on a Display. Notice that sometimes the svg logo at the top of the Presentation sometimes shows, and sometimes does not show. The best way to make it stop showing is to add a second Presentation to the Schedule.

The Network tab of Dev Tools looks correct, it is calling the svg file from the cache, it just doesn't show up on screen.

**Comment by jorey-upenn** [comment]
Note that when served from our infrastructure, I can reliably make the SVG reappear by touching the file on the server, or renaming it and updating the presentation to use the new URL. In either case, it only reappears temporarily.

**Comment by donnapep** [comment]
@robb-price I'm not seeing an SVG file being used in that Presentation. Can you clarify?

**Comment by robb-price** [comment]
@donnapep My apologies, that was a link to the wrong Presentation. I have updated it to have a link to the correct Presentation.

**Comment by donnapep** [comment]
@robb-price Thx. What OS are you running Player on? Does it occur on all OSes?

**Comment by donnapep** [comment]
Closing as this is a Rise Cache issue.
