### ISSUE TITLE
Image does not update when referenced file is replaced with an identically named file.

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/widget-image#12]
* This refers to the testing version of the widget, not production.

Steps to reproduce:
1.  Add image widget beta to a presentation.
2.  Specify image for widget.
3.  Publish presentation.
4.  Using the storage app, overwrite the file (same name) with a different image.

Result:
Image never changes (at least not within a couple of hours).

How it should work:
New image should be shown within 15 (to 60?) minutes?

Additional Notes:
* The URL for the image has pointed to both production storage and test storage with the same results
* As indicated by the presentation link, this is rvauser not rva-test
* Widget URL: http://s3.amazonaws.com/widget-image-test/0.1.1/dist/widget.html
* Widget UI: http://s3.amazonaws.com/widget-image-test/0.1.1/dist/settings.html

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=f7c827f7-e536-4d29-b8b8-7ba67ec5a8e9?cid=e514fd51-fadd-4e19-94af-f92549772c7f

OS:
Xubuntu 14.04

Chrome Ver:
Version 41.0.2272.118 (64-bit)

**Comment by alanclayton** [comment]
@mfisher11 can you let me know if this is an issue still with the production version of the Widget?

**Comment by mfisher11** [comment]
@alanclayton This does not occur in the current production version.  Given the age of the issue, and the fact that the testing version was likely pushed to prod long ago, should I close this out?  Thanks.
