### ISSUE TITLE
Image Widget not showing Images, mixed content error.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-image#128]
**How to recreate?**
1. Add any image (Rise Storage or other) to a Presentation.
2. Schedule that Presentation to appear on a Display.

**What happens?**
The image does not appear. Console displays a mixed content error.

**What should happen?**
Images should appear normally.

**Resources**
Display: https://apps.risevision.com/displays/details/GG5H75E4TK4V?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957
Schedule: https://apps.risevision.com/schedules/details/0ded4e6b-e4d7-4bd0-ab7b-8f67d138998a?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957
Presentation (Rise Storage): https://apps.risevision.com/editor/workspace/6b736b7c-ec50-469f-95df-2d26c5cf1812/?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957
Presentation (3rd Party Host): https://apps.risevision.com/editor/workspace/2e23e5f0-6a38-45c8-bb0a-db1a8a10fb0d/?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957
Screenconnect Session: https://connect.risevision.com/Host#Access/Blake%20Freeman//96f84584-77d8-4a91-b4f3-2352667e9c41

![consoleerror1](https://user-images.githubusercontent.com/8458926/28975040-38e1c9a2-78fe-11e7-825c-4cf622ebbdb5.png)

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate Possible Image Issue](https://trello.com/c/qj3ZNQJb/5142-investigate-possible-image-issue)

**Comment by alanclayton** [comment]
Issue introduced with RisePlayerElectron 2017.08.03.16.42. Reverted to previous version and will work on fix for the issue that was introduced before resuming release.
