### ISSUE TITLE
Multiple Image instances configured for single file are crashing Viewer

### ISSUE THREAD

**Issue by stulees** [Rise-Vision/widget-image#144]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Creative Sprint Backlog](https://trello.com/b/oq3ozPGH/creative) after you've submitted the issue*

- Operating System Version: Ubuntu 14.04.5 x 32-bit
- Player Version: RisePlayerElectron 2018.04.10.17.21 Professional
- Viewer Version: 2-01-201804091627

##### What is the expected behavior?
One or multiple instances of Image widget in a presentation configured for folder should display content indefinitely without a problem. 

##### What is the actual behavior?
Image widget configured for folder is eventually crashing Viewer. The problem can be escalated quicker when there is more than one instance of the widget configured for folder in a presentation. 

##### What steps can be taken to replicate the problem? 

1.Add a Image Widget and configure for a folder of images. The images should be a mix of sizes, small (under 1mb) to large (+10mb).
2. Add a second Image Widget instance and configure for a different folder of images. The images should be a mix of sizes, small (under 1mb) to large (+10mb). 
3. Update Display to show content. 
4. Monitor display and logs in BQ for a Viewer crash. The BQ query to run and check for this is:

```
SELECT * FROM [client-side-events:Installer_Events.events2018XXXX]
where display_id = "XXXXXXXX"
and event = "viewer webContents crashed"
order by ts DESC
```

**Comment by sheadarlison** [comment]
@jungeunyoon @rudibravo FYI

**Comment by stulees** [comment]
Image using RLS for single file has fixed the issue. Additional details can be found on https://trello.com/c/5f1uyQME/5403-defect-144-help-content-w-image-widget-2 . Closing this issue.
