### ISSUE TITLE
Image does not appear when Folder name in Rise Storage contains an apostrophe

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/widget-image#15]
Steps to reproduce:
1. Create a folder in storage with an apostrophe in the folder name and uploading an image file to the folder
2. Add Image widget to a presentation and choose a file from the folder created in step 1
3. Preview or assign presentation to display and run in Player

Result:
Image never appears

How it should work:
Image should appear even if there is an apostrophe in the folder name

Additional Notes:
1) This issue doesn't occur using Image item, Image Folder widget, Video widget or Video Folder widget.
2) This issue also occurs when setting an image from the same folder as a background image in a Placeholder (eg  Image Item, Image widget)

Link to Presentation:

rvauser.appspot.com/#/PRESENTATION_MANAGE/id=3a7dd5d7-43a4-4789-9ac1-e5e39ec90c71?cid=cd7cb86b-8134-4c41-996c-d1ca82e5a1a9

OS:
Windows 7
ChromeOS

Chrome Ver:
Windows 44.0.2403.89 (32 bit)
ChromeOS 43.0.2357.134

**Comment by alanclayton** [comment]
@AlexKolenoff @donnapep can this be closed now?

**Comment by donnapep** [comment]
@alanclayton I'm fine with closing it.

**Comment by AlexKolenoff** [comment]
@alanclayton @donnapep Per the question on the Trello card, I was verifying this and it seems that it works now for the Image widget, but there is still a problem when the image (coming from a folder with an apostrophe) is set as a background to the Image widget or the Image item.  I am just double-checking that on my display but wanted to find out if that part of the issue was looked into.

**Comment by alanclayton** [comment]
@AlexKolenoff The issue related to background image is related to RVA not the Image Widget. Do you think that needs to be a priority? Can it wait to be fixed with the new Editor?

**Comment by AlexKolenoff** [comment]
@alanclayton No, I don't think it needs to be a priority, the workaround is just to create a new folder without an apostrophe.

**Comment by alanclayton** [comment]
@AlexKolenoff Thanks.
