### ISSUE TITLE
Image Widget incorrect rotation

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/widget-image#154]
**How To Recreate**
Go to https://apps.risevision.com/editor/workspace/c0bb40ec-bc41-42ca-ab3f-e3e94dab04fd/?cid=833e25ca-ca97-4dfe-a47c-aca1648ca9cb and select 'Preview'

**What Happens**
Images in Storage that are correctly rotated in file and thumbnail preview are turned 90 degress in a Presentation (both Display and Preview)

**What Should Happen**

Image Widget should follow the rotation orientation of the image file.

**Result**
![img_1411](https://user-images.githubusercontent.com/11826611/41040932-c940c8b4-696b-11e8-8dc7-9d1910c6d12a.jpg)
![img_1410](https://user-images.githubusercontent.com/11826611/41040935-cc9a087c-696b-11e8-9608-a404433be4a8.jpg)

**Source**
![image](https://user-images.githubusercontent.com/11826611/41040963-dc55811a-696b-11e8-95ea-52dd055149ae.png)

**Comment by sheadarlison** [comment]
Hey @RV-Adrian this is the same as this issue https://github.com/Rise-Vision/widget-image/issues/19 

It was closed two years ago because I don't think it was possible to fix in the widget, but a lot has changed in two years and there might be some JS libraries we could use to fix this. We'll take another look and get back to you.

Thanks

**Comment by RV-Adrian** [comment]
@sheadarlison Oh wow, classic! 
Sounds good, thanks.

**Comment by sheadarlison** [comment]
Need to update this article if/when fixed https://help.risevision.com/hc/en-us/articles/115005291506-My-image-is-rotated-in-the-wrong-direction

**Comment by santiagonoguez** [comment]
@sheadarlison @RV-Adrian  Closing this issue, follow up:
https://github.com/Rise-Vision/rise-launcher-electron/issues/748

**Comment by colby-maughan** [comment]
@sheadarlison It looks like this issue is prevalent again - we've had a few tickets regarding images being rotated the wrong direction and clearing exif data has resolved them. Could someone take a look and see if this needs revisiting?

**Comment by sheadarlison** [comment]
@colby-maughan this is a storage issue, not an Image Widget issue. See here: https://github.com/Rise-Vision/storage-server/issues/287 

We can't fix this on the client side. 

Thanks
