### ISSUE TITLE
Images are being downloaded every few minutes

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/widget-image#17]
Steps to Reproduce
1. Add the Image widget to a presentation and add an image files from Rise Storage.  Note the file size.
2. Assign the presentation to player and run on display for at least an hour or more
3. Watch this folder and identify the file download(s) (from the file size you noted above in step 1): "C:\users\[username]\AppData\Local\Temp"

Result:
The same file is downloaded to C:\users\[username]\AppData\Local\Temp every few minutes.  For example, the image I chose was downloaded 11 times in 50 minutes.  If the files playing on a client's display are large enough and numerous enough, the drive could become full without manual intervention.

How it should work:
The file should not be downloaded so frequently.

Link to Presentation:
rvauser.appspot.com/#/PRESENTATION_MANAGE/id=55366f34-6e6a-4891-8f43-398b0af9dae9?cid=cd7cb86b-8134-4c41-996c-d1ca82e5a1a9

OS:
Windows 7

Chrome Ver:
44.0.2403.130 (CAP)

**Comment by alanclayton** [comment]
Corrected w/ https://github.com/Rise-Vision/web-component-rise-storage/pull/57. Closing issue
