### ISSUE TITLE
When a file is moved to trash the Image Widget should no longer show it

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-image#180]
https://github.com/Rise-Vision/rise-launcher-electron/issues/757

https://trello.com/c/ZutE6CTU/4634-2-defect-757-storage-if-a-file-exists-in-trash-it-will-display-instead-of-a-file-with-the-same-path-and-filename-in-storage

**Comment by jungeunyoon** [comment]
Fix deployed as part of Player issue 757. https://github.com/Rise-Vision/rise-launcher-electron/issues/757

---

**Problem** 
When a file is deleted in Storage, nothing is done on Image Widget other than logging it.

**Solution** 
When a file is deleted in Storage, it should be removed from being displayed. 

**How to validate** 
1. Use Image Widget with single image in Storage.
2. Delete image from Storage.
3. The image should be cleared and a message should be displayed.
