### ISSUE TITLE
Image widget showing a folder requires player restart if all folder files are removed

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/widget-image#185]
1. Create a presentation showing a folder of images with one image widget set to play until done
2. Confirm display is rotating through all images
3. While display is still running, trash one image
4. Confirm display rotation has updated to no longer include that image.
5. While display is still running, re-upload the image 
6. Confirm display rotation now includes all images as before
7. While display is still running, trash all files in the folder
8. Display says "Unable to display any files." and logs "No files to display" to BQ.
9. **Re-upload files.**
10. **Display continues to show "Unable to display any files"** even though local storage has downloaded the new files and broadcasted FILE-UPDATE (visible in local logs).

![unable-to-display-any-files](https://user-images.githubusercontent.com/1511535/47240742-5ac2ec80-d3b7-11e8-95b3-339a4f87c79f.png)

**Comment by stulees** [comment]
@tejohnso I cannot recreate this on ChrOS Beta or Electron Beta players. When I re-upload files the display does not continue to show "Unable to display any files" message. However, the issue I do see is that, after deleting all files in the folder followed by re-uploading multiple files in the same upload, only 1 of the images is displayed and the widget never rotates to the other images. At that point, if you then upload any more files, then the Widget starts rotating all of them. 

I will look into fixing this problem I describe above. @sheadarlison FYI

**Comment by stulees** [comment]
@tejohnso I was now able to recreate the issue. If the re-upload of files is > 2 files, the message "Unable to display any files" persists and there is an error in the dev console. Working on isolating the issue. @sheadarlison FYI

**Comment by stulees** [comment]
The issue has been fixed with #186 and validated on both ChrOS and Electron Players. @tejohnso @PatrickA-RiseVision

**Comment by sheadarlison** [comment]
Thanks @stulees
