### ISSUE TITLE
If you have a folder set to PUD, and you empty that folder and put no more files into it, on all OS' it sits on the last image of that folder

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-image#189]
### What is the expected behavior?
If there are no files in the folder, it should not play anything.

### What is the actual behavior?
When the Image Widget is set to PUD, the last image will come up after roughly 15 - 20 seconds, and sit on that image and not change.

### What steps can be taken to replicate the problem?
1. Create a Presentation with a Placeholder.
2. Add the Image Widget, point to a folder with files, make the Image Widget PUD.
3. Once all files have downloaded and are playing, delete all files from the folder.
4. Notice that the Placeholder goes blank, and then after 15 - 20 seconds, the last image from the folder comes back and stays there.

For further clarification:  https://goo.gl/cWM7NR

**Comment by stulees** [comment]
This has been fixed with #192
