### ISSUE TITLE
Files with &amp; in the name cause an error message

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-image#193]

**Comment by santiagonoguez** [comment]
Seems to be an issue in the presentation editor, not the widget; details in the following card:

https://trello.com/c/4Iw9aUBQ/6296-widget-image-issue-193-3

Assigning to Apps team.

**Comment by sheadarlison** [comment]
@santiagonoguez @stulees closing this issue given we've opened the apps one. 

Thanks
