### ISSUE TITLE
Image Widget displaying "please wait while your image is downloaded" after reboot on certain ChromeOS and Windows Displays

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/widget-image#196]
**Expected Behavior**
After a Media Player reboots images set in the image widget should load every time.

**Actual Behavior**
After rebooting the Media Player the image widget displays "please wait while your image is downloaded" instead of loading the image and doesn't recover until after another reboot/restart of Rise Player.

**Steps to reproduce**
I was unable to reproduce this.
It happens randomly on multiple Media Players under a specific user's account.

**Details of Media Player where issue has occurred multiple times:** 
Operating System | Chrome OS 12239.92.1
Player Version | RisePlayer 2019.09.04.9951 Free
Viewer Version | 2-01-201910222027
Browser Version | Chrome 76.0.3809.136

**Comment by stulees** [comment]
Full conclusions [here](https://trello.com/c/1XPtPiXV/7354-issue-196-investigation-image-widget-displaying-please-wait-while-your-image-is-downloaded-after-reboot-on-certain-chromeos-and#comment-5dd6b1b894b0f1196db38edf), in summary this Display is running fine, issue could never be reproduced, and logs indicate that the display upgraded to newer ChrOS player versions which may have inadvertently fixed what problem user was seeing.
