### ISSUE TITLE
run locally problem

### ISSUE THREAD

**Issue by mmoignet** [Rise-Vision/widget-image#20]
I'm a very beginner in Rise Vision app developpment and I am sorry if my question is irrelevant here.

I've install everything for testing widget-image on my computer.

gulp build is OK

but when I try to install the widget preview app using the link : http://192.254.220.36/~rvi/widget-preview/

The 192.254.220.36 host seem not to be alive.
Could you help me to find this app?
Regards
Michel Moignet
France

**Comment by stulees** [comment]
@mmoignet Apologies Michel, the link in the README appears to be outdated. We will get this corrected, thanks for letting us know. Please visit the Widget Preview repo for correct download links and information - https://github.com/Rise-Vision/widget-preview

**Comment by mmoignet** [comment]
thank you very much,
Using the new link I've found the widget_preview app
Michel
