### ISSUE TITLE
Error reporting rise cache not running when in webplayer

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/widget-image#226]
Seeing multiple E000000019 errors when showing a presentation with Viewer `type=webplayer`.

For example with `https://widgets.risevision.com/viewer/?type=webplayer&id=[my-test-display-id]` 

The query

```
SELECT
  *
FROM
  `endpoint-event-logs.logs.eventLog`
WHERE
  DATE(timestamp) = "2021-05-07"
  AND endpointId = "[my-test-display-id]"
```

returns 

```
widget-image | 0.1.1 | ERROR | E000000019 | rise cache not running | {"event":"error","event_details":"rise cache not running"}
```

**Comment by stulees** [comment]
@tejohnso Issue closed with #230 . Image and video widgets were not recognizing that that should use Content Sentinel for `webplayer`. This has been corrected. Closing.
