### ISSUE TITLE
Schedule can only handle 4 items containing Image Folder Widget

### ISSUE THREAD

**Issue by ashleighalmeida** [Rise-Vision/widget-image#29]
Issue:

User has presentations that contain 3 image folder widgets in each. 
When adding the fifth presentation, the image folder widgets will freeze and not move on to the next image. Or, one image folder will work and the other will not.
When the schedule contains 4 items, the image folder widgets will play successfully.

What I've done to replicate:

Downloaded user's storage folders and uploaded them onto my own.
Created presentations with 3 image folder widgets within my own company.
Added presentations one by one until the error occurred.
On the 5th presentation, the glitch started to occur.

See: https://apps.risevision.com/schedules/details/e125773f-6fc5-4f17-a77f-7f80097df5df?cid=4ebf4461-1830-4ec2-a9bd-64cc32e60499

Demo: https://drive.google.com/a/risevision.com/file/d/0B5_6TQ6T_mw1QkN0ZkJFa21SQVU/view?usp=sharing

**Comment by robb-price** [comment]
@alanclayton What is the ETA on this?

**Comment by alanclayton** [comment]
@robb-price it is current being worked on. Please follow https://trello.com/c/oUS2maSa/1094-2-image-issue-29

**Comment by donnapep** [comment]
Fixed by PR #34.
