### ISSUE TITLE
Image not loading - in RiseCache.log Handshake alert: unrecognized name 

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-image#42]
**How to recreate**
Refer to this <a href="http://rva.risevision.com/#/PRESENTATION_MANAGE/id=ee620a99-cb01-44bc-a9f9-558c2a97e2de?cid=960b72df-9af7-476b-8a47-b67ded4c779d"> presentation</a> and show on live Display.
Within the presentation is an Image Widget referencing to an external link like <a href="https://www.unifiedbrandmedia.com/data/azcwr/images/2.jpg">this</a>.
Go to RiseCache.log 

This also happens when the RiseCache.jar is replaced with the latest version that was tested that also included this <a href="https://github.com/Rise-Vision/rise-cache/pull/10 ">PR</a>.

This does not seem to happen if the image is on Rise Storage.

**Expected Results**
The correct image (one that is externally hosted) to show in the Placeholder.

**Actual Results**
Instead of an image, the Placeholder throws an error "There was a problem retrieving the file from Rise Cache". When running the DisplayID in BQ (for RiseCache events) it does not state that any error messages have been thrown. See http://g.recordit.co/LyHUmPJeLk.gif

**Comment by lapinnoir** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/1777441305

**Comment by hcs0** [comment]
Closing since RiseCache issue

**Comment by hcs0** [comment]
FYI @rodrigopavezi
