### ISSUE TITLE
Store pops up when pressing Enter in Settings

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/widget-image#48]
When changing Image Widget settings, if you press Enter, a Store window pops up.
My suggestion is that Enter key should work as Save. 

![](https://trello-attachments.s3.amazonaws.com/567c186a338e7ac5598ac5bc/1425x814/4a0b9f8471e413b70b5e4491c197048e/edit.gif)

**Comment by alanclayton** [comment]
Issue resolved.
