### ISSUE TITLE
Image won't show up if file name has spaces and brackets

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-image#57]
Presentation here: https://apps.risevision.com/editor/workspace/4302b213-9f64-4cf5-b070-2388e1882dcf/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

Preview here: http://preview.risevision.com/?type=presentation&id=4302b213-9f64-4cf5-b070-2388e1882dcf&showui=false

Image here: https://storage.googleapis.com/risemedialibrary-f114ad26-949d-44b4-87e9-8528afc76ce4/weather-background-3%20(1)%20(1).png

**Comment by donnapep** [comment]
Fixed by PR #58
