### ISSUE TITLE
Feature Request: Pull images from directories

### ISSUE THREAD

**Issue by matthewlswanson** [Rise-Vision/widget-image#61]
This widget is very nice, but it can only pull 1 image from an external source (i.e. google drive). I need to have it connect to a folder with several hundred images and don't want the users to have to add the widget hundreds of times

**Comment by alanclayton** [comment]
@matthewlswanson We do not have plans to support showing a folder of images from a 3rd party server. I'd recommend using Rise Storage (https://storage.risevision.com) to show a folder of images. Thanks!

**Comment by matthewlswanson** [comment]
I would love to use Rise Storage but there is no way to control who has
access to what folders and this is essential to our setup :(

On Mon, Feb 29, 2016 at 11:20 AM, Alan Clayton <notifications@github.com>
wrote:

> @matthewlswanson <https://github.com/matthewlswanson> We do not have
> plans to support showing a folder of images from a 3rd party server. I'd
> recommend using Rise Storage (https://storage.risevision.com) to show a
> folder of images. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rise-Vision/widget-image/issues/61#issuecomment-190342657>
> .
>



-- 
Matthew Swanson
Network Administrator
George Fox University
503.554.2588

**Comment by alanclayton** [comment]
@matthewlswanson take a look at the response I just posted in the [Community](https://community.risevision.com/rise_vision_inc/topics/alternative-options-to-rise-storage?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=16662147#reply_16662147) and let me know if that helps.

Thanks!
