### ISSUE TITLE
Bucket error when configuring production Image Widget.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-image#7]
1. Log in to Rise Vision root company.
2. Add placeholder
3. Add Content -> Image Widget
4. Click Configure
Error message: NoSuchBucketThe specified bucket does not existwidgetimage8169DC955F94E2CBrvbZJdNpsoO+y9EHK6tk5jeNEjulZ5a8011jC5QXwJaDY9b6atm5lva9tjJqHVOgE365qHsZLmU=

http://www.screencast.com/t/LYB21inv8c

**Comment by donnapep** [comment]
The Gadget URLs aren't set up correctly - http://screencast.com/t/X0nPTDaifCsL. You're missing the dash.
