### ISSUE TITLE
When a Presentation contains duplicated Image Widgets, not all Widgets appear

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-image#70]
**How to recreate**
Use the **Full Screen Image** Template 
Duplicate a few instances of the Image Widget within the template, creating 10 Image Widgets in total
For each of the Image Widgets, link to a different external URL .jpg image
User this <a href="https://apps.risevision.com/editor/workspace/587a79c9-b075-442e-8ce8-d571b23c79b1/true?cid=960b72df-9af7-476b-8a47-b67ded4c779d">presentation</a> as a reference.

**What happens**
On preview, open Developer Console > Sources > in iFrame_c0_pre0 I’m only seeing 6 images (or 6 instances of widget.html).  Whereas there should be 10.

<img width="1025" alt="screen shot 2016-04-22 at 6 08 32 pm" src="https://cloud.githubusercontent.com/assets/5868781/14756271/0ba9af68-08b6-11e6-91b7-c19355f8c749.png">

**What should happen**
When editing a template, a user should be able to duplicate the Image Widget, add their own image URL and preview.

**Notes**
I was able to resolve the issue for a user by deleting the duplicated Image Widgets that did not show on preview and adding it as a new Image Widget.

**Comment by hcs0** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/hcs@risevision.com/conversations/4598962516

**Comment by stulees** [comment]
@hcs0 Can you clarify what the problem is with Image Widget? In following the steps, it seems like this is more of a new editor issue and/or Viewer.  Thanks

**Comment by hcs0** [comment]
Closing to log in apps repo
