### ISSUE TITLE
Play Until Done is a duration option on a single image widget.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-image#74]
**How to recreate**
1. Add an Image Widget with an Image in a presentation
2. Add another Widget of any type into the same placeholder
3. Edit the Image Widget Playlist item and select "Play Until Done"

**What happens**
The presentation never moves on to the next item in the playlist, because there is no timer to determine when an image is done playing.

**What should happen**
Play until done should not be an option on a single image in the Image Widget.

**Notes*
Presentation: http://bit.ly/1QSVhqq

**Comment by ByronDarlison** [comment]
@btfrise @alanclayton isn't duration, in this case restricting PUD, outside the scope of what the widget can control?

**Comment by alanclayton** [comment]
Not going to fix due to this being a design issue with Duration/PUD defined outside the Widget and user error (PUD does not apply to a single image)
