### ISSUE TITLE
WebP images will not validate when attempting to load from Storage

### ISSUE THREAD

**Issue by Fantastitech** [Rise-Vision/widget-image#75]
<b> How it works now</b>
Using the Image Widget, loading an image from Storage using the "Single Image" or "Folder of Images" buttons with a WebP image will cause a file type validation error that can not be bypassed:
![screenshot from 2016-06-06 14-35-07](https://cloud.githubusercontent.com/assets/14909394/15838810/e05d654a-2bf4-11e6-853b-bfbc05482af5.png)

When a WebP image is added using the Custom URL option and you check the "Remove validation" box, it will work fine.

<b>How it should work</b>
WebP should be an accepted file type in the Image Widget.

**Comment by alanclayton** [comment]
@Fantastitech a fix for this issue was deployed yesterday. Let us know if you see anything else.

Thanks!
