### ISSUE TITLE
Says Image does not exist or has been moved to trash but it does exist and has not been moved to trash

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/widget-image#78]
Placeholder: ph2

Presentation: https://apps.risevision.com/editor/workspace/ccfc1542-a354-4b1f-9767-a440517d0e01/?cid=6b26789a-405c-4e25-a653-ec4c7c4e5eed

Preview: http://preview.risevision.com/?type=presentation&id=ccfc1542-a354-4b1f-9767-a440517d0e01

Image: https://commondatastorage.googleapis.com/risemedialibrary-6b26789a-405c-4e25-a653-ec4c7c4e5eed/wlu_logo585.png

![wlu_logo585](https://cloud.githubusercontent.com/assets/9273546/16589708/4dcca514-42a2-11e6-871a-b952c147198e.png)

![screen shot 2016-07-05 at 11 20 13 am](https://cloud.githubusercontent.com/assets/9273546/16589781/8f0eb058-42a2-11e6-83d3-6826b9cbe9dc.png)

**Comment by stulees** [comment]
@sheadarlison I'm not able to reproduce this when looking at the presentation and previewing:

http://www.screencast.com/t/t9st01CY6

http://www.screencast.com/t/BOdk3WswA

Where did you get the link from for the image you mentioned above? Thanks

**Comment by sheadarlison** [comment]
@stulees Sorry this was a client presentation so I needed a quick fix. I fixed the issue by uploading the file to storage. However, when it was pulling as a custom URL it wasn't working. The URL was from one of their other presentations. Thanks

**Comment by stulees** [comment]
@sheadarlison I've tried using the Custom URL input with the following URLs:

- https://commondatastorage.googleapis.com/risemedialibrary-6b26789a-405c-4e25-a653-ec4c7c4e5eed/wlu_logo585.png
- https://storage.googleapis.com/risemedialibrary-6b26789a-405c-4e25-a653-ec4c7c4e5eed/wlu_logo585.png
- http://s3.amazonaws.com/stu-testing/sample_images/wlu_logo585.png (uploaded to my own bucket on Amazon)

All of the above worked, so I'm still unable to reproduce this. 

The only way the Widget would have displayed "The selected image does not exist or has been moved to Trash." is if the Widget processed the file as a **storage file** and the request returned no files. Do you know what the original URL was that was used? 

@alanclayton FYI

**Comment by sheadarlison** [comment]
@stulees The original URL was http://commondatastorage.googleapis.com/risemedialibrary-6b26789a-405c-4e25-a653-ec4c7c4e5eed/wlu_logo585.png

**Comment by stulees** [comment]
@sheadarlison That was one of the URLs I tried. I've changed my presentation to use that URL, see here - https://apps.risevision.com/editor/workspace/544611bb-27d5-4a77-8235-ebcf0e8c508b/?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

Without being able to see what was previously happening I don't think I can investigate it any further. @sheadarlison @alanclayton Okay to close?

**Comment by sheadarlison** [comment]
@stulees must have been a one time issue. I think this is good to close. Thanks

**Comment by stulees** [comment]
@sheadarlison Okay thanks
