### ISSUE TITLE
Image Widget set to display folder of webp images shows "The selected folder does not show any supported image formats".

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-image#79]
**How to recreate**
1. Create a new presentation with the Image Widget
2. Configure the Image Widget to display a folder full of .webp images
3. Save and preview presentation

**What happens**
Presentation shows "The selected folder does not show any supported image format"

**What should happen**
The Widget should show all .webp images.

**Comment by stulees** [comment]
@btfrise Fixed with PR #80
