### ISSUE TITLE
Animated GIF hosted at https://media.giphy.com causes player to restart

### ISSUE THREAD

**Issue by raydurkin** [Rise-Vision/widget-image#81]
An animated GIF that is hosted at https://media.giphy.com's web site when inserted using the image widget in the presentation will cause the Rise Player to restart about every hour.  When the animated GIF is put into Rise Storage and added to the presentation, the Rise Player stop restarting.

To recreate:
Presentation with animated GIF image items linked to https://media.giphy.com here: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=b4dc5955-ac9b-490c-8777-5d945c004ada?cid=54928942-bd3d-45cb-88de-c3d970744111

Look at placeholder called image_left.   The first playlist item (chaplain) and the third playlist item are both image widgets.  The first is pointed to this URL: https://media.giphy.com/media/3orieUW2FEWyAw34gE/giphy.gif
The second image is pointed to this URL: https://media.giphy.com/media/3orieZ9jHS0pF3EJy0/giphy.gif

Running this presentation on a Windows 10 compute stick causes the player to restart about once per hour.

Now download those images and put them in Rise Storage and add them into the playlist instead of the previous links and the player does not restart.

Here is a link to the presentation that is using those same animated GIFs placed in Rise Storage:  https://rva.risevision.com/#/PRESENTATION_MANAGE/id=03b72aaa-e282-4fc0-a25e-96791b6b2ed3?cid=bb776dc3-6e7b-4993-98dd-511f6aa1dbd7

**Comment by alanclayton** [comment]
Correction has been deployed.
